### ISSUE TITLE
疑似损坏

### ISSUE THREAD

**Issue by SnowCutieOwO** [Robert-Du0001/docsify-footnote#3]
使用的是最新版的脚本，正常注释如 
```
[^1]

[^1]: xxx
```
不会显示，相反则会显示带超链接的文本 ^1，超链接末尾则为注释文本
这是什么情况？
已知文章内容与该问题无关

**Comment by Robert-Du0001** [comment]
这就是正常的引用脚注，有什么问题吗？

```
[^1]

asda[^1]

xxx[^2]

[^1]: asda

[^2]: xxx
```

显示：

![7M$1HUX6IRD8VIVTVD`49BA](https://github.com/Robert-Du0001/docsify-footnote/assets/29976859/7c5ecf92-966a-4631-8da8-257a6fd06243)

**Comment by SnowCutieOwO** [comment]
> 这就是正常的引用脚注，有什么问题吗？
> 
> ```
> [^1]
> 
> asda[^1]
> 
> xxx[^2]
> 
> [^1]: asda
> 
> [^2]: xxx
> ```
> 
> 显示：
> 
> ![7M$1HUX6IRD8VIVTVD`49BA](https://github.com/Robert-Du0001/docsify-footnote/assets/29976859/7c5ecf92-966a-4631-8da8-257a6fd06243)
> 
> 

我也不知道我那个文档有什么问题，相同的格式就是不识别，晚点我可以把我的Docsify模板发来你检查一下吗

**Comment by Robert-Du0001** [comment]
问题能复现吗？能复现的话就直接发个示例，不能复现的话你再把你那个发我看看吧。

**Comment by SnowCutieOwO** [comment]
> 问题能复现吗？能复现的话就直接发个示例，不能复现的话你再把你那个发我看看吧。

我那个文档里面不管在哪里都是脚注失效，其他的正常

**Comment by Robert-Du0001** [comment]
你试试在脚注后面加个换行，看是否正常

![$YI%W61JESJ5F~HH 4GC%CT](https://github.com/Robert-Du0001/docsify-footnote/assets/29976859/6271396e-59c9-4630-8835-26e71e80dacf)

**Comment by SnowCutieOwO** [comment]
> 你试试在脚注后面加个换行，看是否正常
> 
> ![$YI%W61JESJ5F~HH 4GC%CT](https://github.com/Robert-Du0001/docsify-footnote/assets/29976859/6271396e-59c9-4630-8835-26e71e80dacf)
> 

无法生效，怪就怪在连VSCode里的预览都能正常显示，实际塞进去跑却用不了

**Comment by Robert-Du0001** [comment]
那你后面把你的代码发我吧，可能是哪有个bug

**Comment by SnowCutieOwO** [comment]
> 那你后面把你的代码发我吧，可能是哪有个bug

先谢谢了，我代码晚点放在这里）
[Docsify.zip](https://github.com/Robert-Du0001/docsify-footnote/files/14801408/Docsify.zip)

**Comment by SnowCutieOwO** [comment]
> 那你后面把你的代码发我吧，可能是哪有个bug

已经发了，看一下

**Comment by Robert-Du0001** [comment]
换行符问题，你这边用的是\r\n，我这已经处理了。你看看还有没有问题，没有的话就把issue关了

**Comment by SnowCutieOwO** [comment]
> 换行符问题，你这边用的是\r\n，我这已经处理了。你看看还有没有问题，没有的话就把issue关了

我看了一下我这边还是不行，好奇怪

**Comment by Robert-Du0001** [comment]
引用地址用这个

```js
<script src="//cdn.jsdelivr.net/npm/docsify-footnote@1.0.6/dist/docsify-footnote.min.js"></script>
```

**Comment by SnowCutieOwO** [comment]
> 引用地址用这个
> 
> ```js
> <script src="//cdn.jsdelivr.net/npm/docsify-footnote@1.0.6/dist/docsify-footnote.min.js"></script>
> ```

匹配到冒号之后的内容就又不匹配了，脚注里插链接就炸

```
[^1]: 可惜的是，国内服务商并不会主动提供这些。若你需要相似的教程，请访问[Runoob：MySQL安装及搭建教程](https://www.runoob.com/mysql/mysql-install.html)。
```
显示为
1. 可惜的是，国内服务商并不会主动提供这些。若你需要相似的教程，请访问[Runoob：MySQL安装及搭建教程](https

**Comment by Robert-Du0001** [comment]
可以了，使用

```js
<script src="//cdn.jsdelivr.net/npm/docsify-footnote@1.0.7/dist/docsify-footnote.min.js"></script>
```

你这些情况太特殊了，都没考虑到。。。😂

**Comment by SnowCutieOwO** [comment]
> 可以了，使用
> 
> ```js
> <script src="//cdn.jsdelivr.net/npm/docsify-footnote@1.0.7/dist/docsify-footnote.min.js"></script>
> ```
> 
> 你这些情况太特殊了，都没考虑到。。。😂

谢谢义父！😭😭😭😭
