### ISSUE TITLE
脚注在标题上引用缩放不正常

### ISSUE THREAD

**Issue by SnowCutieOwO** [Robert-Du0001/docsify-footnote#4]
如题，下文的格式会使脚注和标题字体一样大

```Markdown
# ABC[^1]

[^1]: a footnote
```

会显示为：

# ABC<u>[1]</u>

1. a footnote <u>↑</u>

**Comment by Robert-Du0001** [comment]
这个都是这样吧 我看vscode也是这样

**Comment by SnowCutieOwO** [comment]
> 这个都是这样吧 我看vscode也是这样

但是只有正文会缩放看着有点怪）

**Comment by Robert-Du0001** [comment]
这个其实没有缩放，是转成<sup>标签的，html的<sup>标签在正文是会有缩小的样式，在标题就没有缩小了。这个都是这样的，如果觉得标题那看着有点怪，可以考虑不把脚注放标题那。😂

**Comment by Robert-Du0001** [comment]
这个其实没有缩放，是转成`<sup />`标签的，html的`<sup />`标签在正文是会有缩小的样式，在标题就没有缩小了。这个都是这样的，如果觉得标题那看着有点怪，可以考虑不把脚注放标题那。😂

**Comment by SnowCutieOwO** [comment]
> 这个其实没有缩放，是转成`<sup />`标签的，html的`<sup />`标签在正文是会有缩小的样式，在标题就没有缩小了。这个都是这样的，如果觉得标题那看着有点怪，可以考虑不把脚注放标题那。😂

好，感谢义父解答😭
别的拓展回复速度都没你快啊，感动坏了
